### ISSUE TITLE
Error when running in Sata 18

### ISSUE THREAD

**Issue by wkirui** [PovertyAction/ipachecksetup#2]
---> (unknown function error): 
 - version 18.0
  - syntax varname [if] [in] [, Separate(str) MISSing Local(name local) Clean MATROW(name) MATCELL(name) HEXa
> decimal ]
  - tempname frm
  - local useframe 0
  - if ("`if'`in'" != "") {
  = if ("if (regexm(type, "^(begin)") & regexm(type, "group|repeat"))" != "") {
**unknown function ()**
  ---------------------

---> also this error when the hfc input template is not provided (the link to the hfc template in github needs to be updated).
Prefilling HFC Inputs ...
file
    https://raw.githubusercontent.com/PovertyAction/high-frequency-checks/master/xlsx
    > /hfc_inputs.xlsm not found
r(601);

**Comment by iabaako** [comment]
This program hasn't been updated to work with the DMS 4. Kindly make it private for now until it is updated. When update it will be added as a program in the DMS.
